//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL_MVC.ServiceReferenceDepartamento {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDepartamento.IDepartamentoCRUD")]
    public interface IDepartamentoCRUD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoCRUD/Add", ReplyAction="http://tempuri.org/IDepartamentoCRUD/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SLWCF.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Producto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Proveedor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Area))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Departamento))]
        SLWCF.Result Add(ML.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoCRUD/Add", ReplyAction="http://tempuri.org/IDepartamentoCRUD/AddResponse")]
        System.Threading.Tasks.Task<SLWCF.Result> AddAsync(ML.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoCRUD/Update", ReplyAction="http://tempuri.org/IDepartamentoCRUD/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SLWCF.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Producto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Proveedor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Area))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Departamento))]
        SLWCF.Result Update(ML.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoCRUD/Update", ReplyAction="http://tempuri.org/IDepartamentoCRUD/UpdateResponse")]
        System.Threading.Tasks.Task<SLWCF.Result> UpdateAsync(ML.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoCRUD/Delete", ReplyAction="http://tempuri.org/IDepartamentoCRUD/DeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Departamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Area))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Producto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Proveedor))]
        SLWCF.Result Delete(int odDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoCRUD/Delete", ReplyAction="http://tempuri.org/IDepartamentoCRUD/DeleteResponse")]
        System.Threading.Tasks.Task<SLWCF.Result> DeleteAsync(int odDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoCRUD/GetAll", ReplyAction="http://tempuri.org/IDepartamentoCRUD/GetAllResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SLWCF.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Producto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Proveedor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Area))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Departamento))]
        SLWCF.Result GetAll(ML.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoCRUD/GetAll", ReplyAction="http://tempuri.org/IDepartamentoCRUD/GetAllResponse")]
        System.Threading.Tasks.Task<SLWCF.Result> GetAllAsync(ML.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoCRUD/GetById", ReplyAction="http://tempuri.org/IDepartamentoCRUD/GetByIdResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Departamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Area))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Producto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Proveedor))]
        SLWCF.Result GetById(int idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamentoCRUD/GetById", ReplyAction="http://tempuri.org/IDepartamentoCRUD/GetByIdResponse")]
        System.Threading.Tasks.Task<SLWCF.Result> GetByIdAsync(int idDepartamento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDepartamentoCRUDChannel : PL_MVC.ServiceReferenceDepartamento.IDepartamentoCRUD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DepartamentoCRUDClient : System.ServiceModel.ClientBase<PL_MVC.ServiceReferenceDepartamento.IDepartamentoCRUD>, PL_MVC.ServiceReferenceDepartamento.IDepartamentoCRUD {
        
        public DepartamentoCRUDClient() {
        }
        
        public DepartamentoCRUDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DepartamentoCRUDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartamentoCRUDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartamentoCRUDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SLWCF.Result Add(ML.Departamento departamento) {
            return base.Channel.Add(departamento);
        }
        
        public System.Threading.Tasks.Task<SLWCF.Result> AddAsync(ML.Departamento departamento) {
            return base.Channel.AddAsync(departamento);
        }
        
        public SLWCF.Result Update(ML.Departamento departamento) {
            return base.Channel.Update(departamento);
        }
        
        public System.Threading.Tasks.Task<SLWCF.Result> UpdateAsync(ML.Departamento departamento) {
            return base.Channel.UpdateAsync(departamento);
        }
        
        public SLWCF.Result Delete(int odDepartamento) {
            return base.Channel.Delete(odDepartamento);
        }
        
        public System.Threading.Tasks.Task<SLWCF.Result> DeleteAsync(int odDepartamento) {
            return base.Channel.DeleteAsync(odDepartamento);
        }
        
        public SLWCF.Result GetAll(ML.Departamento departamento) {
            return base.Channel.GetAll(departamento);
        }
        
        public System.Threading.Tasks.Task<SLWCF.Result> GetAllAsync(ML.Departamento departamento) {
            return base.Channel.GetAllAsync(departamento);
        }
        
        public SLWCF.Result GetById(int idDepartamento) {
            return base.Channel.GetById(idDepartamento);
        }
        
        public System.Threading.Tasks.Task<SLWCF.Result> GetByIdAsync(int idDepartamento) {
            return base.Channel.GetByIdAsync(idDepartamento);
        }
    }
}
